#username:password@, authSource=admin because in docker-compose, we are providing authentication info
spring.data.mongodb.uri: "mongodb://root:password@localhost:27017/product-service?authSource=admin"